# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.


return <<'END';
0000	0020
0030	0039
0041	005A
005F		
0061	007A
007F	00A0
00A8		
00AA		
00AD		
00AF		
00B2	00B5
00B7	00BA
00BC	00BE
00C0	00D6
00D8	00F6
00F8	200F
2028	202F
203F	2040
2054		
205F	218F
2460	24FF
2776	2793
2C00	2DFF
2E80	3000
3004	3007
3021	302F
3031	FD3D
FD40	FE44
FE47	10FFFF
END
