# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.


return <<'END';
0000	FDCF
FDF0	FFFD
10000	1FFFD
20000	2FFFD
30000	3FFFD
40000	4FFFD
50000	5FFFD
60000	6FFFD
70000	7FFFD
80000	8FFFD
90000	9FFFD
A0000	AFFFD
B0000	BFFFD
C0000	CFFFD
D0000	DFFFD
E0000	EFFFD
F0000	FFFFD
100000	10FFFD
END
