# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.


return <<'END';
0000	0068
006B	012E
0130	0248
024A	0267
0269	029C
029E	02B1
02B3	03F2
03F4	0455
0457		
0459	1D61
1D63	1D95
1D97	1DA3
1DA5	1DA7
1DA9	1E2C
1E2E	1ECA
1ECC	2070
2072	2147
214A	2C7B
2C7D	1D421
1D424	1D455
1D458	1D489
1D48C	1D4BD
1D4C0	1D4F1
1D4F4	1D525
1D528	1D559
1D55C	1D58D
1D590	1D5C1
1D5C4	1D5F5
1D5F8	1D629
1D62C	1D65D
1D660	1D691
1D694	10FFFF
END
