# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.


return <<'END';
0000	002C
002E	00AC
00AE	0589
058B	1805
1807	200F
2012	2E16
2E18	30FA
30FC	FE62
FE64	FF0C
FF0E	FF64
FF66	10FFFF
END
