# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.


return <<'END';
0000	0008
000E	001F
0021	0084
0086	009F
00A1	167F
1681	180D
180F	1FFF
200B	2027
202A	202E
2030	205E
2060	2FFF
3001	10FFFF
END
