# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.


return <<'END';
0000	00AC
00AE	034E
0350	115E
1161	17B3
17B6	180A
180E	200A
2010	2029
202F	205F
2070	3163
3165	FDFF
FE10	FEFE
FF00	FF9F
FFA1	FFEF
FFF9	1D172
1D17B	DFFFF
E1000	10FFFF
END
