# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.


return <<'END';
0000	002C
002E	0589
058B	05BD
05BF	13FF
1401	1805
1807	200F
2016	2052
2054	207A
207C	208A
208C	2211
2213	2E16
2E18	2E19
2E1B	301B
301D	302F
3031	309F
30A1	FE30
FE33	FE57
FE59	FE62
FE64	FF0C
FF0E	10FFFF
END
