# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.


return <<'END';
0000	00B6
00B8	02CF
02D2	063F
0641	07F9
07FB	0E45
0E47	0EC5
0EC7	1842
1844	1AA6
1AA8	1C35
1C37	1C7A
1C7C	3004
3006	3030
3036	309C
309F	30FB
30FF	A014
A016	A60B
A60D	A9CE
A9D0	AA6F
AA71	AADC
AADE	FF6F
FF71	10FFFF
END
