# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.


return <<'END';
0000	09BD
09BF	09D6
09D8	0B3D
0B3F	0B56
0B58	0BBD
0BBF	0BD6
0BD8	0CC1
0CC3	0CD4
0CD7	0D3D
0D3F	0D56
0D58	0DCE
0DD0	0DDE
0DE0	200B
200E	FF9D
FFA0	1D164
1D166	1D16D
1D173	10FFFF
END
