# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.


return <<'END';
09BE		
09D7		
0B3E		
0B57		
0BBE		
0BD7		
0CC2		
0CD5	0CD6
0D3E		
0D57		
0DCF		
0DDF		
200C	200D
FF9E	FF9F
1D165		
1D16E	1D172
END
