# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.


return <<'END';
0000	0021
0023	0026
0028	00AA
00AC	00BA
00BC	2017
2020	2038
203B	300B
3010	301C
3020	FE40
FE45	FF01
FF03	FF06
FF08	FF61
FF64	10FFFF
END
