# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.


return <<'END';
0000	0020
0022	002D
002F	003E
0040	055B
055D		
055F	0588
058A	061E
0620	06D3
06D5	06FF
0703	07F8
07FA	0963
0966	1049
104C	1361
1363	1366
1369	166D
166F	1734
1737	1802
1804	1808
180A	1943
1946	1AA7
1AAC	1B59
1B5C	1B5D
1B60	1C3A
1C3D	1C7D
1C80	203B
203E	2046
204A	2E2D
2E2F	3001
3003	A4FE
A500	A60D
A610	A6F2
A6F4	A6F6
A6F8	A875
A878	A8CD
A8D0	A92E
A930	A9C7
A9CA	AA5C
AA60	ABEA
ABEC	FE51
FE53	FE55
FE58	FF00
FF02	FF0D
FF0F	FF1E
FF20	FF60
FF62	10A55
10A58	11046
11049	110BD
110C2	10FFFF
END
