# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.


return <<'END';
0000	0957
0960	09DB
09DE		
09E0	0A32
0A34	0A35
0A37	0A58
0A5C	0A5D
0A5F	0B5B
0B5E	0F42
0F44	0F4C
0F4E	0F51
0F53	0F56
0F58	0F5B
0F5D	0F68
0F6A	0F75
0F77		
0F79	0F92
0F94	0F9C
0F9E	0FA1
0FA3	0FA6
0FA8	0FAB
0FAD	0FB8
0FBA	2ADB
2ADD	FB1C
FB1E		
FB20	FB29
FB37		
FB3D		
FB3F		
FB42		
FB45		
FB4F	1D15D
1D165	1D1BA
1D1C1	10FFFF
END
