# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.


return <<'END';
0020	007E
00A0	00AC
00AE	05FF
0604	06DC
06DE	070E
0710	17B3
17B6	200A
200C	200D
2010	2027
202F	205F
2065	2069
2070	FEFE
FF00	FFF8
FFFC	110BC
110BE	1D172
1D17B	E0000
E0002	E001F
E0080	10FFFF
END
