# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.


# The name this swash is to be known by, with the format of the mappings in
# the main body of the table, and what all code points missing from this file
# map to.
$utf8::SwashInfo{'To_suc'}{'format'} = 'x'; # positive hex whole number; a code point
$utf8::SwashInfo{'To_suc'}{'missing'} = '<code point>'; # code point maps to itself

return <<'END';
1F80		1F88
1F81		1F89
1F82		1F8A
1F83		1F8B
1F84		1F8C
1F85		1F8D
1F86		1F8E
1F87		1F8F
1F90		1F98
1F91		1F99
1F92		1F9A
1F93		1F9B
1F94		1F9C
1F95		1F9D
1F96		1F9E
1F97		1F9F
1FA0		1FA8
1FA1		1FA9
1FA2		1FAA
1FA3		1FAB
1FA4		1FAC
1FA5		1FAD
1FA6		1FAE
1FA7		1FAF
1FB3		1FBC
1FC3		1FCC
1FF3		1FFC
END
