# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.


# The name this swash is to be known by, with the format of the mappings in
# the main body of the table, and what all code points missing from this file
# map to.
$utf8::SwashInfo{'ToDt'}{'format'} = 's'; # string
$utf8::SwashInfo{'ToDt'}{'missing'} = 'None';

return <<'END';
00A0		Nobreak
00A8		Compat
00AA		Super
00AF		Compat
00B2	00B3	Super
00B4	00B5	Compat
00B8		Compat
00B9	00BA	Super
00BC	00BE	Fraction
00C0	00C5	Canonical
00C7	00CF	Canonical
00D1	00D6	Canonical
00D9	00DD	Canonical
00E0	00E5	Canonical
00E7	00EF	Canonical
00F1	00F6	Canonical
00F9	00FD	Canonical
00FF	010F	Canonical
0112	0125	Canonical
0128	0130	Canonical
0132	0133	Compat
0134	0137	Canonical
0139	013E	Canonical
013F	0140	Compat
0143	0148	Canonical
0149		Compat
014C	0151	Canonical
0154	0165	Canonical
0168	017E	Canonical
017F		Compat
01A0	01A1	Canonical
01AF	01B0	Canonical
01C4	01CC	Compat
01CD	01DC	Canonical
01DE	01E3	Canonical
01E6	01F0	Canonical
01F1	01F3	Compat
01F4	01F5	Canonical
01F8	021B	Canonical
021E	021F	Canonical
0226	0233	Canonical
02B0	02B8	Super
02D8	02DD	Compat
02E0	02E4	Super
0340	0341	Canonical
0343	0344	Canonical
0374		Canonical
037A		Compat
037E		Canonical
0384		Compat
0385	038A	Canonical
038C		Canonical
038E	0390	Canonical
03AA	03B0	Canonical
03CA	03CE	Canonical
03D0	03D2	Compat
03D3	03D4	Canonical
03D5	03D6	Compat
03F0	03F2	Compat
03F4	03F5	Compat
03F9		Compat
0400	0401	Canonical
0403		Canonical
0407		Canonical
040C	040E	Canonical
0419		Canonical
0439		Canonical
0450	0451	Canonical
0453		Canonical
0457		Canonical
045C	045E	Canonical
0476	0477	Canonical
04C1	04C2	Canonical
04D0	04D3	Canonical
04D6	04D7	Canonical
04DA	04DF	Canonical
04E2	04E7	Canonical
04EA	04F5	Canonical
04F8	04F9	Canonical
0587		Compat
0622	0626	Canonical
0675	0678	Compat
06C0		Canonical
06C2		Canonical
06D3		Canonical
0929		Canonical
0931		Canonical
0934		Canonical
0958	095F	Canonical
09CB	09CC	Canonical
09DC	09DD	Canonical
09DF		Canonical
0A33		Canonical
0A36		Canonical
0A59	0A5B	Canonical
0A5E		Canonical
0B48		Canonical
0B4B	0B4C	Canonical
0B5C	0B5D	Canonical
0B94		Canonical
0BCA	0BCC	Canonical
0C48		Canonical
0CC0		Canonical
0CC7	0CC8	Canonical
0CCA	0CCB	Canonical
0D4A	0D4C	Canonical
0DDA		Canonical
0DDC	0DDE	Canonical
0E33		Compat
0EB3		Compat
0EDC	0EDD	Compat
0F0C		Nobreak
0F43		Canonical
0F4D		Canonical
0F52		Canonical
0F57		Canonical
0F5C		Canonical
0F69		Canonical
0F73		Canonical
0F75	0F76	Canonical
0F77		Compat
0F78		Canonical
0F79		Compat
0F81		Canonical
0F93		Canonical
0F9D		Canonical
0FA2		Canonical
0FA7		Canonical
0FAC		Canonical
0FB9		Canonical
1026		Canonical
10FC		Super
1B06		Canonical
1B08		Canonical
1B0A		Canonical
1B0C		Canonical
1B0E		Canonical
1B12		Canonical
1B3B		Canonical
1B3D		Canonical
1B40	1B41	Canonical
1B43		Canonical
1D2C	1D2E	Super
1D30	1D3A	Super
1D3C	1D4D	Super
1D4F	1D61	Super
1D62	1D6A	Sub
1D78		Super
1D9B	1DBF	Super
1E00	1E99	Canonical
1E9A		Compat
1E9B		Canonical
1EA0	1EF9	Canonical
1F00	1F15	Canonical
1F18	1F1D	Canonical
1F20	1F45	Canonical
1F48	1F4D	Canonical
1F50	1F57	Canonical
1F59		Canonical
1F5B		Canonical
1F5D		Canonical
1F5F	1F7D	Canonical
1F80	1FB4	Canonical
1FB6	1FBC	Canonical
1FBD		Compat
1FBE		Canonical
1FBF	1FC0	Compat
1FC1	1FC4	Canonical
1FC6	1FD3	Canonical
1FD6	1FDB	Canonical
1FDD	1FEF	Canonical
1FF2	1FF4	Canonical
1FF6	1FFD	Canonical
1FFE		Compat
2000	2001	Canonical
2002	2006	Compat
2007		Nobreak
2008	200A	Compat
2011		Nobreak
2017		Compat
2024	2026	Compat
202F		Nobreak
2033	2034	Compat
2036	2037	Compat
203C		Compat
203E		Compat
2047	2049	Compat
2057		Compat
205F		Compat
2070	2071	Super
2074	207F	Super
2080	208E	Sub
2090	209C	Sub
20A8		Compat
2100	2101	Compat
2102		Font
2103		Compat
2105	2107	Compat
2109		Compat
210A	2113	Font
2115		Font
2116		Compat
2119	211D	Font
2120		Super
2121		Compat
2122		Super
2124		Font
2126		Canonical
2128		Font
212A	212B	Canonical
212C	212D	Font
212F	2131	Font
2133	2134	Font
2135	2138	Compat
2139		Font
213B		Compat
213C	2140	Font
2145	2149	Font
2150	215F	Fraction
2160	217F	Compat
2189		Fraction
219A	219B	Canonical
21AE		Canonical
21CD	21CF	Canonical
2204		Canonical
2209		Canonical
220C		Canonical
2224		Canonical
2226		Canonical
222C	222D	Compat
222F	2230	Compat
2241		Canonical
2244		Canonical
2247		Canonical
2249		Canonical
2260		Canonical
2262		Canonical
226D	2271	Canonical
2274	2275	Canonical
2278	2279	Canonical
2280	2281	Canonical
2284	2285	Canonical
2288	2289	Canonical
22AC	22AF	Canonical
22E0	22E3	Canonical
22EA	22ED	Canonical
2329	232A	Canonical
2460	2473	Circle
2474	24B5	Compat
24B6	24EA	Circle
2A0C		Compat
2A74	2A76	Compat
2ADC		Canonical
2C7C		Sub
2C7D		Super
2D6F		Super
2E9F		Compat
2EF3		Compat
2F00	2FD5	Compat
3000		Wide
3036		Compat
3038	303A	Compat
304C		Canonical
304E		Canonical
3050		Canonical
3052		Canonical
3054		Canonical
3056		Canonical
3058		Canonical
305A		Canonical
305C		Canonical
305E		Canonical
3060		Canonical
3062		Canonical
3065		Canonical
3067		Canonical
3069		Canonical
3070	3071	Canonical
3073	3074	Canonical
3076	3077	Canonical
3079	307A	Canonical
307C	307D	Canonical
3094		Canonical
309B	309C	Compat
309E		Canonical
309F		Vertical
30AC		Canonical
30AE		Canonical
30B0		Canonical
30B2		Canonical
30B4		Canonical
30B6		Canonical
30B8		Canonical
30BA		Canonical
30BC		Canonical
30BE		Canonical
30C0		Canonical
30C2		Canonical
30C5		Canonical
30C7		Canonical
30C9		Canonical
30D0	30D1	Canonical
30D3	30D4	Canonical
30D6	30D7	Canonical
30D9	30DA	Canonical
30DC	30DD	Canonical
30F4		Canonical
30F7	30FA	Canonical
30FE		Canonical
30FF		Vertical
3131	318E	Compat
3192	319F	Super
3200	321E	Compat
3220	3243	Compat
3244	3247	Circle
3250		Square
3251	327E	Circle
3280	32BF	Circle
32C0	32CB	Compat
32CC	32CF	Square
32D0	32FE	Circle
3300	3357	Square
3358	3370	Compat
3371	33DF	Square
33E0	33FE	Compat
33FF		Square
A770		Super
AC00	D7A3	Canonical
F900	FA0D	Canonical
FA10		Canonical
FA12		Canonical
FA15	FA1E	Canonical
FA20		Canonical
FA22		Canonical
FA25	FA26	Canonical
FA2A	FA2D	Canonical
FA30	FA6D	Canonical
FA70	FAD9	Canonical
FB00	FB06	Compat
FB13	FB17	Compat
FB1D		Canonical
FB1F		Canonical
FB20	FB29	Font
FB2A	FB36	Canonical
FB38	FB3C	Canonical
FB3E		Canonical
FB40	FB41	Canonical
FB43	FB44	Canonical
FB46	FB4E	Canonical
FB4F		Compat
FB50		Isolated
FB51		Final
FB52		Isolated
FB53		Final
FB54		Initial
FB55		Medial
FB56		Isolated
FB57		Final
FB58		Initial
FB59		Medial
FB5A		Isolated
FB5B		Final
FB5C		Initial
FB5D		Medial
FB5E		Isolated
FB5F		Final
FB60		Initial
FB61		Medial
FB62		Isolated
FB63		Final
FB64		Initial
FB65		Medial
FB66		Isolated
FB67		Final
FB68		Initial
FB69		Medial
FB6A		Isolated
FB6B		Final
FB6C		Initial
FB6D		Medial
FB6E		Isolated
FB6F		Final
FB70		Initial
FB71		Medial
FB72		Isolated
FB73		Final
FB74		Initial
FB75		Medial
FB76		Isolated
FB77		Final
FB78		Initial
FB79		Medial
FB7A		Isolated
FB7B		Final
FB7C		Initial
FB7D		Medial
FB7E		Isolated
FB7F		Final
FB80		Initial
FB81		Medial
FB82		Isolated
FB83		Final
FB84		Isolated
FB85		Final
FB86		Isolated
FB87		Final
FB88		Isolated
FB89		Final
FB8A		Isolated
FB8B		Final
FB8C		Isolated
FB8D		Final
FB8E		Isolated
FB8F		Final
FB90		Initial
FB91		Medial
FB92		Isolated
FB93		Final
FB94		Initial
FB95		Medial
FB96		Isolated
FB97		Final
FB98		Initial
FB99		Medial
FB9A		Isolated
FB9B		Final
FB9C		Initial
FB9D		Medial
FB9E		Isolated
FB9F		Final
FBA0		Isolated
FBA1		Final
FBA2		Initial
FBA3		Medial
FBA4		Isolated
FBA5		Final
FBA6		Isolated
FBA7		Final
FBA8		Initial
FBA9		Medial
FBAA		Isolated
FBAB		Final
FBAC		Initial
FBAD		Medial
FBAE		Isolated
FBAF		Final
FBB0		Isolated
FBB1		Final
FBD3		Isolated
FBD4		Final
FBD5		Initial
FBD6		Medial
FBD7		Isolated
FBD8		Final
FBD9		Isolated
FBDA		Final
FBDB		Isolated
FBDC		Final
FBDD	FBDE	Isolated
FBDF		Final
FBE0		Isolated
FBE1		Final
FBE2		Isolated
FBE3		Final
FBE4		Isolated
FBE5		Final
FBE6		Initial
FBE7		Medial
FBE8		Initial
FBE9		Medial
FBEA		Isolated
FBEB		Final
FBEC		Isolated
FBED		Final
FBEE		Isolated
FBEF		Final
FBF0		Isolated
FBF1		Final
FBF2		Isolated
FBF3		Final
FBF4		Isolated
FBF5		Final
FBF6		Isolated
FBF7		Final
FBF8		Initial
FBF9		Isolated
FBFA		Final
FBFB		Initial
FBFC		Isolated
FBFD		Final
FBFE		Initial
FBFF		Medial
FC00	FC63	Isolated
FC64	FC96	Final
FC97	FCDE	Initial
FCDF	FCF4	Medial
FCF5	FD10	Isolated
FD11	FD2C	Final
FD2D	FD33	Initial
FD34	FD3B	Medial
FD3C		Final
FD3D		Isolated
FD50		Initial
FD51		Final
FD52	FD57	Initial
FD58		Final
FD59		Initial
FD5A	FD5B	Final
FD5C	FD5D	Initial
FD5E	FD5F	Final
FD60	FD61	Initial
FD62		Final
FD63		Initial
FD64		Final
FD65		Initial
FD66	FD67	Final
FD68		Initial
FD69	FD6A	Final
FD6B		Initial
FD6C		Final
FD6D		Initial
FD6E	FD6F	Final
FD70		Initial
FD71		Final
FD72	FD73	Initial
FD74	FD76	Final
FD77		Initial
FD78	FD7C	Final
FD7D		Initial
FD7E	FD82	Final
FD83		Initial
FD84	FD85	Final
FD86		Initial
FD87		Final
FD88	FD8A	Initial
FD8B		Final
FD8C	FD8F	Initial
FD92	FD95	Initial
FD96	FD97	Final
FD98		Initial
FD99	FD9C	Final
FD9D		Initial
FD9E	FDB3	Final
FDB4	FDB5	Initial
FDB6	FDB7	Final
FDB8		Initial
FDB9		Final
FDBA		Initial
FDBB	FDC2	Final
FDC3	FDC5	Initial
FDC6	FDC7	Final
FDF0	FDFC	Isolated
FE10	FE19	Vertical
FE30	FE44	Vertical
FE47	FE48	Vertical
FE49	FE4F	Compat
FE50	FE52	Small
FE54	FE66	Small
FE68	FE6B	Small
FE70		Isolated
FE71		Medial
FE72		Isolated
FE74		Isolated
FE76		Isolated
FE77		Medial
FE78		Isolated
FE79		Medial
FE7A		Isolated
FE7B		Medial
FE7C		Isolated
FE7D		Medial
FE7E		Isolated
FE7F		Medial
FE80	FE81	Isolated
FE82		Final
FE83		Isolated
FE84		Final
FE85		Isolated
FE86		Final
FE87		Isolated
FE88		Final
FE89		Isolated
FE8A		Final
FE8B		Initial
FE8C		Medial
FE8D		Isolated
FE8E		Final
FE8F		Isolated
FE90		Final
FE91		Initial
FE92		Medial
FE93		Isolated
FE94		Final
FE95		Isolated
FE96		Final
FE97		Initial
FE98		Medial
FE99		Isolated
FE9A		Final
FE9B		Initial
FE9C		Medial
FE9D		Isolated
FE9E		Final
FE9F		Initial
FEA0		Medial
FEA1		Isolated
FEA2		Final
FEA3		Initial
FEA4		Medial
FEA5		Isolated
FEA6		Final
FEA7		Initial
FEA8		Medial
FEA9		Isolated
FEAA		Final
FEAB		Isolated
FEAC		Final
FEAD		Isolated
FEAE		Final
FEAF		Isolated
FEB0		Final
FEB1		Isolated
FEB2		Final
FEB3		Initial
FEB4		Medial
FEB5		Isolated
FEB6		Final
FEB7		Initial
FEB8		Medial
FEB9		Isolated
FEBA		Final
FEBB		Initial
FEBC		Medial
FEBD		Isolated
FEBE		Final
FEBF		Initial
FEC0		Medial
FEC1		Isolated
FEC2		Final
FEC3		Initial
FEC4		Medial
FEC5		Isolated
FEC6		Final
FEC7		Initial
FEC8		Medial
FEC9		Isolated
FECA		Final
FECB		Initial
FECC		Medial
FECD		Isolated
FECE		Final
FECF		Initial
FED0		Medial
FED1		Isolated
FED2		Final
FED3		Initial
FED4		Medial
FED5		Isolated
FED6		Final
FED7		Initial
FED8		Medial
FED9		Isolated
FEDA		Final
FEDB		Initial
FEDC		Medial
FEDD		Isolated
FEDE		Final
FEDF		Initial
FEE0		Medial
FEE1		Isolated
FEE2		Final
FEE3		Initial
FEE4		Medial
FEE5		Isolated
FEE6		Final
FEE7		Initial
FEE8		Medial
FEE9		Isolated
FEEA		Final
FEEB		Initial
FEEC		Medial
FEED		Isolated
FEEE		Final
FEEF		Isolated
FEF0		Final
FEF1		Isolated
FEF2		Final
FEF3		Initial
FEF4		Medial
FEF5		Isolated
FEF6		Final
FEF7		Isolated
FEF8		Final
FEF9		Isolated
FEFA		Final
FEFB		Isolated
FEFC		Final
FF01	FF60	Wide
FF61	FFBE	Narrow
FFC2	FFC7	Narrow
FFCA	FFCF	Narrow
FFD2	FFD7	Narrow
FFDA	FFDC	Narrow
FFE0	FFE6	Wide
FFE8	FFEE	Narrow
1109A		Canonical
1109C		Canonical
110AB		Canonical
1D15E	1D164	Canonical
1D1BB	1D1C0	Canonical
1D400	1D454	Font
1D456	1D49C	Font
1D49E	1D49F	Font
1D4A2		Font
1D4A5	1D4A6	Font
1D4A9	1D4AC	Font
1D4AE	1D4B9	Font
1D4BB		Font
1D4BD	1D4C3	Font
1D4C5	1D505	Font
1D507	1D50A	Font
1D50D	1D514	Font
1D516	1D51C	Font
1D51E	1D539	Font
1D53B	1D53E	Font
1D540	1D544	Font
1D546		Font
1D54A	1D550	Font
1D552	1D6A5	Font
1D6A8	1D7CB	Font
1D7CE	1D7FF	Font
1F100	1F10A	Compat
1F110	1F12A	Compat
1F12B	1F12E	Circle
1F130	1F14F	Square
1F190		Square
1F200	1F202	Square
1F210	1F23A	Square
1F240	1F248	Compat
1F250	1F251	Circle
2F800	2FA1D	Canonical
END
