# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.


return <<'END';
0600	0603
0606	060B
060D	061A
061E		
0620	063F
0641	064A
0656	065E
066A	066F
0671	06DC
06DE	06FF
0750	077F
FB50	FBC1
FBD3	FD3D
FD50	FD8F
FD92	FDC7
FDF0	FDFC
FE70	FE74
FE76	FEFC
10E60	10E7E
END
