# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.


return <<'END';
0000	034E
0350	115E
1161	2064
206A	3163
3165	FF9F
FFA1	FFEF
FFF9	DFFFF
E0001		
E0020	E007F
E0100	E01EF
E1000	10FFFF
END
