# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.


return <<'END';
034F		
115F	1160
2065	2069
3164		
FFA0		
FFF0	FFF8
E0000		
E0002	E001F
E0080	E00FF
E01F0	E0FFF
END
