# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.


return <<'END';
0000	02AF
02B9	02BF
02C2	02DF
02E5	0344
0346	0379
037B	1D2B
1D62	1D77
1D79	1D9A
1DC0	208F
2095	216F
2180	24CF
24EA	2C7C
2C7E	A76F
A771	10FFFF
END
