# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.


return <<'END';
02B0	02B8
02C0	02C1
02E0	02E4
0345		
037A		
1D2C	1D61
1D78		
1D9B	1DBF
2090	2094
2170	217F
24D0	24E9
2C7D		
A770		
END
