# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.


return <<'END';
0860	08FF
1AB0	1AFF
1C80	1CCF
2FE0	2FEF
A9E0	A9FF
AAE0	AAFF
AB30	ABBF
10200	1027F
102E0	102FF
10350	1037F
103E0	103FF
104B0	107FF
10860	108FF
10940	109FF
10A80	10AFF
10B80	10BFF
10C50	10E5F
10E80	10FFF
110D0	11FFF
12480	12FFF
13430	167FF
16A40	1AFFF
1B100	1CFFF
1D250	1D2FF
1D380	1D3FF
1D800	1EFFF
1F650	1F67F
1F780	1FFFF
2A6E0	2A6FF
2B820	2F7FF
2FA20	DFFFF
E0080	E00FF
E01F0	EFFFF
END
