# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.


return <<'END';
0000	3005
3008	3020
302A	3037
303B	33FF
4DB6	4DFF
9FCC	F8FF
FA2E	FA2F
FA6E	FA6F
FADA	1FFFF
2A6D7	2A6FF
2B735	2B73F
2B81E	2F7FF
2FA1E	10FFFF
END
